---
- name: Install Ruby and Bundle
  hosts: all
  become: true

  roles:
    - app

  # tasks:
  # - name: Install packages
  #   apt: "name={{ item }} state=present"
  #   whith_item:
  #     - ruby-full
  #     - ruby-bundler
  #     - build-essential
