---
- name: Install and configure MongoDB
  hosts: module_db_db
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
    #db_host: 10.128.0.30

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
