name: Run playbook ansible tests

on:
  push:
    branches-ignore: main
    # branches:
    #   - "master"
  pull_request:
    branches-ignore: main
    # branches:
    #   - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "ansible"
  # deployAnsible:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: ./.github/actions/ansible
  #     with:
  #       playbook: playbook.yml
  #       inventory: localhost
