name: Packer tests

on:
  push:
    branches-ignore: main
    # branches:
    #   - "master"
  pull_request:
    branches-ignore: main
    # branches:
    #   - "master"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer jobs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer

      # # build artifact
      # - name: Build Artifact
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: build
      #     arguments: "-color=false -on-error=abort"
      #     target: packer
      #   env:
      #     PACKER_LOG: 1
