name: Run tests for OTUS homework

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "key.examples.json"
        json: '{ "id": "ajeju3ti95vrql9djjit" }'
        dir: './'

    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Checkout repo with tests
      uses: actions/checkout@v2
      with:
        repository: "express42/otus-homeworks"
        ref: 2021-08
        path: "./otus-homeworks/"

    - name: Run tests
      run: curl https://raw.githubusercontent.com/express42/otus-homeworks/2021-08/run.sh | bash
